%% 初始化路径
imageFileNames = {'C:\Users\Admin\Desktop\d435ifigure\figure2_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure3_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure4_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure5_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure6_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure7_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure8_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure9_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure10_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure11_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure12_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure13_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure14_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure15_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure17_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure18_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure19_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure20_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure21_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure22_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure23_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure24_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure25_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure26_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure27_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure28_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure29_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure30_Color.png',...
    'C:\Users\Admin\Desktop\d435ifigure\figure31_Color.png'};

%% 标定流程
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames, 'MinCornerMetric', 0.15);
imageFileNames = imageFileNames(imagesUsed);
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);
worldPoints = generateWorldPoints(detector, 'SquareSize', 30);

[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'ImageSize', [mrows, ncols]);

%% 稳健的可视化


% 重投影误差
figure('Name', 'Reprojection Errors');
showReprojectionErrors(cameraParams);

% 残差分布
figure('Name', 'Residuals');
res = reshape(cameraParams.ReprojectionErrors, [], 2);
scatter(res(:,1), res(:,2), 6, 'filled');
grid on; axis equal; hold on;
line([-1 1], [0 0], 'Color', 'r'); line([0 0], [-0.8 0.8], 'Color', 'r');
xlabel('X Error'); ylabel('Y Error'); title('Residuals Distribution');

% 外参可视化
figure('Name', 'Extrinsics');
showExtrinsics(cameraParams, 'CameraCentric');
figure('Name', 'PatternCentric');
showExtrinsics(cameraParams, 'PatternCentric'); % 这里改回了兼容名

% 效果对比
undistortedImg = undistortImage(originalImage, cameraParams);
figure('Name', 'Undistort Result');
imshowpair(originalImage, undistortedImg, 'montage');


fprintf('\n平均重投影误差: %.4f pixels\n', cameraParams.MeanReprojectionError);
displayErrors(estimationErrors, cameraParams);


